server {
    listen 80;
    server_name _;

    # Serve static frontend files from React's /dist build
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # This is critical for React Router routes to work directly
        try_files $uri $uri/ /index.html;
    }

    # Intercept any requests specifically starting with /api and map to backend container
    location /api/ {
        # The word 'backend' here will refer to the Docker Compose service name we create in Phase 4
        proxy_pass http://backend:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
